use_frameworks!

platform :ios, '9.0'

target 'LRSImagePreview_Example' do
  pod 'LRSImagePreview', :path => '../'

  target 'LRSImagePreview_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
