source 'https://github.com/CocoaPods/Specs.git'
source 'git@coding.jiamiantech.com:ce/jiamianSpecs.git'

use_frameworks!

platform :ios, '11.0'

target 'LRSImagePreview_Example' do
  pod 'LRSImagePreview', :path => '../'
  pod 'TZImagePickerController'
  pod 'BlocksKit'
  target 'LRSImagePreview_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
